"""empty message

Revision ID: df9b6551b255
Revises: de3b53020b3d
Create Date: 2020-07-14 20:48:26.533456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df9b6551b255'
down_revision = 'de3b53020b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=120)),
               nullable=False)
   
    op.alter_column('Venue', 'country',
               
               nullable=True)
    op.alter_column('Artist', 'country',
               
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'country',
               
               nullable=True)
    op.alter_column('Artist', 'country',
               
               nullable=True)
    
    # ### end Alembic commands ###
